#!/bin/sh

if [[ $(uname -s) == "Darwin" ]]; then
    alias copy="pbcopy"
    alias paste="pbpaste"

    # Applications
    alias chrome="open -a 'Google Chrome'"
    alias safari="open -a 'Safari'"

    alias fix-osx-plex="sudo codesign --force --sign - /Applications/Plex\ Home\ Theater.app/"
    alias remove-dsstore="find . -name '*.DS_Store' -type f -delete"
    alias clear-cache="sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder; say DNS cache flushed"

    # show / hide dotfiles in Finder
    alias show-dotfiles="defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app"
    alias hide-dotfiles="defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app"
fi
