#!/bin/sh

if [[ $(uname -s) == "Darwin" ]]; then
	alias copy="pbcopy"
	alias paste="pbpaste"

	# Applications
	alias chrome="open -a 'Google Chrome'"
	alias safari="open -a 'Safari'"

	alias fix-osx-plex="sudo codesign --force --sign - /Applications/Plex\ Home\ Theater.app/"
	alias remove-dsstore="find . -name '*.DS_Store' -type f -delete"

	# show / hide dotfiles in Finder
	alias show-dotfiles="defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app"
	alias hide-dotfiles="defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app"

	os_version=$(sw_vers -productVersion)
	flushdns="sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder; say DNS cache flushed"

	if [[ ! "$os_version" == "10.11.4" && ! "$os_version" == "10.11.6" && ! "$os_version" == "10.12.6" ]]; then
		echo "DNS clear-cache alias not set for this version of OSX"
	else
		alias clear-cache="$flushdns"
	fi

fi
