#!/bin/sh

git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

cp $HOME/.shell-config/setup/default.vimrc $HOME/.vimrc

echo "Start vim and run the following command \":PluginInstall\""
# vim +BundleInstall +qall
